// const data: Array<any> = [
//   {
//     name: 'Rock',
//     prediction: 0.08,
//     color: colors.rock,
//     legendFontColor: colors.rock,
//     legendFontSize: 15,
//   },
//   {
//     name: 'Pop',
//     prediction: 0.25,
//     color: colors.pop,
//     legendFontColor: colors.pop,
//     legendFontSize: 15,
//   },
//   {
//     name: 'Rap',
//     prediction: 0.18,
//     color: colors.rap,
//     legendFontColor: colors.rap,
//     legendFontSize: 15,
//   },
//   {
//     name: 'Country',
//     prediction: 0.05,
//     color: colors.country,
//     legendFontColor: colors.country,
//     legendFontSize: 15,
//   },
//   {
//     name: 'EDM',
//     prediction: 0.12,
//     color: colors.edm,
//     legendFontColor: colors.edm,
//     legendFontSize: 15,
//   },
//   {
//     name: 'Metal',
//     prediction: 0.07,
//     color: colors.metal,
//     legendFontColor: colors.metal,
//     legendFontSize: 15,
//   },
//   {
//     name: 'Classical',
//     prediction: 0.1,
//     color: colors.classical,
//     legendFontColor: colors.classical,
//     legendFontSize: 15,
//   },
//   {
//     name: 'Jazz',
//     prediction: 0.15,
//     color: colors.jazz,
//     legendFontColor: colors.jazz,
//     legendFontSize: 15,
//   },
// ]
